[fix] Make can output of `Multiple possible types`
vuedoc/md pull request #16
Opened 2018-04-22 14:00 UTC by ota-meshi

input:
```vue
  props: {
    propB: [String, Number],
  }
```

output:
```md
## props 
- `propB` ***String|Number***
```

reference:
https://vuejs.org/v2/guide/components-props.html#Prop-Validation
`propB `

2018-04-23 08:33 UTC, demsking requested changes
Thank you for this PR :-)

2018-04-23 08:33 UTC, demsking commented on lib/markdown.js
> +    return type.elements.map((e) => e.name).join('|')
What is the meaning of the `e` variable?

2018-04-23 08:33 UTC, demsking commented on lib/markdown.js
> +    return type.elements.map((e) => e.name).join('|')
Could you provide a more meaningful variable name please?

2018-04-23 11:42 UTC, ota-meshi commented
@demsking Thank you for review!
I changed the variable name, as your requested.
Please check again it.

2018-04-23 12:29 UTC, demsking approved these changes

2018-04-23 12:31 UTC, merged

2018-04-23 12:33 UTC, demsking commented
Merged to the `develop` branch. I'll release a new version soon

2018-05-02 04:15 UTC, demsking commented
Released: [@vuedoc/md@1.2.0](https://github.com/vuedoc/md/releases/tag/v1.2.0)